# Generated by Django 5.2.7 on 2026-03-27 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='email',
        ),
    ]
